# Generated by Django 4.2.8 on 2024-10-09 07:53

from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AquaticLifeEncyclopedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('discovered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=100, null=True)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField(blank=True, default=2024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_info_unique_id', models.CharField(max_length=50, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('river_location', models.CharField(max_length=50, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('year', models.IntegerField(blank=True, default=2024, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.studentinformation')),
            ],
        ),
        migrations.CreateModel(
            name='CardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=webapp.models.generate_unique_id, max_length=50, unique=True)),
                ('photo', models.ImageField(default='SOME STRING', upload_to='result_images/')),
                ('observation_date_images', models.ImageField(default='SOME STRING', max_length=500, upload_to='result_images/')),
                ('observation_place_images_1', models.ImageField(default='SOME STRING', max_length=500, upload_to='result_images/')),
                ('observation_place_images_2', models.ImageField(default='SOME STRING', max_length=500, upload_to='result_images/')),
                ('river_state_images', models.ImageField(default='SOME STRING', max_length=500, upload_to='result_images/')),
                ('living_thing_consideration_images', models.ImageField(default='SOME STRING', max_length=500, upload_to='result_images/')),
                ('year', models.IntegerField(blank=True, default=2024, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.studentinformation')),
            ],
        ),
    ]
