# Generated by Django 4.2.8 on 2024-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageposition',
            name='illustration_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
