# Generated by Django 5.0 on 2024-04-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_studentinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinformation',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='cardinformation',
            name='fish',
        ),
    ]
