# Generated by Django 5.0 on 2024-05-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_cardinformation_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinformation',
            name='living_thing_consideration_images',
            field=models.ImageField(default='SOME STRING', upload_to='result_images/'),
        ),
        migrations.AddField(
            model_name='cardinformation',
            name='observation_date_images',
            field=models.ImageField(default='SOME STRING', upload_to='result_images/'),
        ),
        migrations.AddField(
            model_name='cardinformation',
            name='observation_place_images_1',
            field=models.ImageField(default='SOME STRING', upload_to='result_images/'),
        ),
        migrations.AddField(
            model_name='cardinformation',
            name='observation_place_images_2',
            field=models.ImageField(default='SOME STRING', upload_to='result_images/'),
        ),
        migrations.AddField(
            model_name='cardinformation',
            name='river_state_images',
            field=models.ImageField(default='SOME STRING', upload_to='result_images/'),
        ),
        migrations.AddField(
            model_name='cardinformation',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.studentinformation'),
        ),
    ]
