# Generated by Django 4.2.8 on 2024-05-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_cardinformation_cutout_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinformation',
            name='observation_date_images',
            field=models.ImageField(default='SOME STRING', max_length=500, upload_to='result_images/'),
        ),
    ]
