# Generated by Django 4.2.8 on 2024-05-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_cardinformation_observation_date_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinformation',
            name='living_thing_consideration_images',
            field=models.ImageField(default='SOME STRING', max_length=500, upload_to='result_images/'),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='observation_place_images_1',
            field=models.ImageField(default='SOME STRING', max_length=500, upload_to='result_images/'),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='observation_place_images_2',
            field=models.ImageField(default='SOME STRING', max_length=500, upload_to='result_images/'),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='river_state_images',
            field=models.ImageField(default='SOME STRING', max_length=500, upload_to='result_images/'),
        ),
    ]
