# Generated by Django 5.0 on 2024-06-18 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_cardinformation_living_thing_consideration_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.studentinformation')),
            ],
        ),
    ]
