# Generated by Django 5.0 on 2024-06-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_cardinformation_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinformation',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='imageposition',
            name='unique_id',
        ),
    ]
