# Generated by Django 5.0 on 2024-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_imageposition_card_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageposition',
            name='card_info',
        ),
        migrations.AlterField(
            model_name='imageposition',
            name='unique_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
