# Generated by Django 5.0 on 2024-06-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_remove_imageposition_card_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageposition',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='imageposition',
            name='card_info_unique_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
