# Generated by Django 5.0 on 2024-07-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_remove_imageposition_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageposition',
            name='river_location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
