# Generated by Django 5.0 on 2024-07-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_imageposition_river_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquaticLifeEncyclopedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_url', models.URLField(blank=True, null=True)),
                ('discovered', models.BooleanField(default=False)),
            ],
        ),
    ]
