# Generated by Django 4.2.8 on 2024-07-04 17:21

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_imageposition_river_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinformation',
            name='unique_id',
            field=models.CharField(default=webapp.models.generate_unique_id, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='imageposition',
            name='card_info_unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
