# Generated by Django 5.0 on 2024-07-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_aquaticlifeencyclopedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquaticlifeencyclopedia',
            name='model_url',
        ),
        migrations.AddField(
            model_name='aquaticlifeencyclopedia',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
