# Generated by Django 4.2.8 on 2024-07-04 18:17

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_cardinformation_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinformation',
            name='unique_id',
            field=models.CharField(default=webapp.models.generate_unique_id, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='imageposition',
            name='card_info_unique_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
