# Generated by Django 5.0 on 2024-08-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_remove_aquaticlifeencyclopedia_model_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
