# Generated by Django 4.2.8 on 2024-07-04 18:37

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_cardinformation_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinformation',
            name='unique_id',
            field=models.CharField(default=webapp.models.generate_unique_id, max_length=50, unique=True),
        ),
    ]
