# Generated by Django 5.0 on 2024-08-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_studentinformation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
