# Generated by Django 5.0 on 2024-09-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_studentinformation_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinformation',
            name='year',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
        migrations.AddField(
            model_name='imageposition',
            name='year',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='year',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
    ]
