# Generated by Django 5.0 on 2024-09-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_cardinformation_year_imageposition_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinformation',
            old_name='student_name',
            new_name='name_id',
        ),
    ]
