version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: elementary_school_webapp
      MYSQL_ROOT_PASSWORD: vdkfan5106
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d  # 初期化スクリプトのディレクトリをマウント

  web:
    build: .
    command: sh -c "until nc -z db 3306; do echo 'Waiting for MySQL...'; sleep 2; done && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=elementary_school_webapp
      - DATABASE_USER=root
      - DATABASE_PASSWORD=vdkfan5106
      - DATABASE_HOST=db
    depends_on:
      - db

volumes:
  mysql_data: